-- Migration: Patch legacy orders table columns
-- Description: Adds any missing orders columns required by the current app model

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS order_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS date TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS subtotal DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS delivery_fee DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS discount DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS total DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS status INTEGER,
    ADD COLUMN IF NOT EXISTS delivery_address TEXT,
    ADD COLUMN IF NOT EXISTS delivery_latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS delivery_longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS delivery_address_comment TEXT,
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(100),
    ADD COLUMN IF NOT EXISTS payment_method_id VARCHAR(10),
    ADD COLUMN IF NOT EXISTS payment_transaction_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS payment_error_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS payment_error_message TEXT,
    ADD COLUMN IF NOT EXISTS payment_attempts INTEGER,
    ADD COLUMN IF NOT EXISTS saved_card_token VARCHAR(255),
    ADD COLUMN IF NOT EXISTS estimated_delivery_time TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS actual_delivery_time TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS estimated_delivery_minutes_min INTEGER,
    ADD COLUMN IF NOT EXISTS estimated_delivery_minutes_max INTEGER,
    ADD COLUMN IF NOT EXISTS branch_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS branch_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS branch_address TEXT,
    ADD COLUMN IF NOT EXISTS branch_phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS poster_spot_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS poster_incoming_order_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS poster_transaction_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS counted_towards_loyalty BOOLEAN,
    ADD COLUMN IF NOT EXISTS loyalty_points_spent DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS loyalty_points_earned_pending DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS loyalty_points_earned_actual DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS receipt_url TEXT,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS comment TEXT,
    ADD COLUMN IF NOT EXISTS courier_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS courier_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS courier_rating DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS courier_photo_url TEXT,
    ADD COLUMN IF NOT EXISTS courier_vehicle VARCHAR(100),
    ADD COLUMN IF NOT EXISTS courier_license_plate VARCHAR(50),
    ADD COLUMN IF NOT EXISTS courier_phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS courier_latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS courier_longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS courier_location_last_updated TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS service_mode INTEGER,
    ADD COLUMN IF NOT EXISTS promo_code VARCHAR(100),
    ADD COLUMN IF NOT EXISTS promo_discount_amount DECIMAL(18, 2),
    ADD COLUMN IF NOT EXISTS promo_discount_percentage DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS user_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS user_order_count INTEGER,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS fcm_token TEXT;
